config/routes.rb
Blog::Application.routes.draw do

  devise_for :users
  resources :categories do
    resources :posts
  end 
  resources :posts
  resources :comments
  
  match 'admin' => 'admin#index'
  match 'publish' => 'admin#publish'
  
  root :to => 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  has_many :comments
  before_validation :rich_text
  
  self.per_page = 10
    
  default_scope :order => 'updated_at desc'  # Order by most recent dates
  scope :pub, where(:published => true) # Only published posts
  scope :unpub, where(:published => false) # Only unpublished posts
  scope :recent, limit(10) # Recent posts

  def to_s
    self.title
  end
  
  # SEO-oriented URLs
  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end
  
  # Search terms to be used with Amazon Products API to display related products
  def terms
    return self.keywords unless self.keywords.blank?
    "search #{self.title}"
  end  
  
  def cat_title
    self.category.title unless self.category.blank?
  end

  validates_presence_of :title, :category
  validates_length_of :title, :within => 3..50
  validates_uniqueness_of :title
  
  private
  
  # 'Rich text' codes to replace before saving. These allow posters
  # To use codes instead of HTML tags to stylize text in the body.
  # Use ///text\\\ for italics, [[[text]]] for bold
  def rich_text
    [ [/\[\[\[/, '<b>'], 
      [/\]\]\]/, '</b>'],
      [/\/\/\//, '<i>'],
      [/\\\\\\/, '</i>']     
    ].each do |rule|
      self.body = self.body.gsub(rule[0], rule[1])
    end
  end
      
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :admin_auth, :except => [:index, :show]

  def index
    if params[:category_id]
      @category = Category.find(params[:category_id]) 
      @posts = @category.posts.pub.paginate(:page => params[:page])      
      @page_title = @category
    else
      @posts = Post.pub.paginate(:page => params[:page])
      @page_title = 'All Posts'
    end

    respond_to do |format|
      format.html 
    end
  end

  def show
    @bad_comment = flash[:bad_comment] #workaround for flash not showing
    @post = Post.find(params[:id])    
    
    if @bad_comment
    	@comment = @bad_comment
   	else  	
	    @comment = Comment.new
	  end
    @comments = @post.comments
    
    # Shows Amazon products, given a valid Amazon Products API key in config
    # Remove comments to enable.
    #s = Search.new(@post.terms)  #search on title if no terms
    #@items = s.items.first(3)
    #@result = s.result

    @items = {}  # Comment out this line after providing your Amazon info.
    

    respond_to do |format|
      if @post.published? || current_user.try(:admin?)
        format.html
      else
        format.html { redirect_to posts_path, alert: 'That post is not available.' }
      end
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html 
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_path, notice: 'Post was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_admin.html.erb
<h2><%= link_to post.title, post %></h2>
<h3><%= post.subtitle %></h3>
<%= post.updated_at.strftime("%b %d, %Y") %>
<h4>Posted in <i><%= link_to post.category, category_posts_path(post.category) %></i></h4>
<%= link_to 'Edit', edit_post_path(post) %> - <%= link_to 'Show', post %><br/>
<%= button_to 'Publish', {:action => 'publish', :id => post.id } %>
<br/><br/>
<hr/>

app/views/posts/_book.html.erb
<div class='box' id='books' >
 <div class='boxtop'><div></div></div>
  <div class='boxcontent'>
	Related items:<br/>	
	<% @items.each do |item|%>
	<%# @result.xml %>
		<p class="bookpic">
			<%= image_tag item.image %>
		</p>
		<p>
			<%= link_to 'See this product on Amazon', item.url %><br/>
			<i><%= item.title %></i><br/>
			<%= item.author %>.<br/>
			<%= item.price %>
		</p>
	<% end %>
  </div>
 <div class='boxbottom'><div></div></div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p><%= f.label :title %><br />
  <%= f.text_field :title %></p>
  
  <p><%= f.label :subtitle %><br />
  <%= f.text_field :subtitle %></p>
  
  <p><%= f.label :category %><br />
  <%= collection_select(:post, :category_id, Category.all, :id, :title, :prompt => true) %></p>
  
  <p><%= f.label "Amazon Keywords: type 'search' and keywords, or list comma-separated ASINs" %><br/>
  <%= f.text_field :keywords %>
  </p>  
	
  <p><%= f.label :body %>
  	-- Use /// and \\\ for italics or [[[ and ]]] for bold.
  <%= f.text_area :body, :size => "60x12" %></p>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= javascript_include_tag "admin.js" %>

app/views/posts/_header.html.erb
<div class="datetag">
	<span class="date"><%= post.updated_at.strftime("%d") %></span>
	<span class="month"><%= post.updated_at.strftime("%b") %></span>
	<span class="year"><%= post.updated_at.strftime("%Y") %></span>
</div>
<h2><%= link_to post.title, post %></h2>
<h3><%= post.subtitle %></h3>
<h4>Posted in <i><%= link_to post.category, category_posts_path(post.category) %></i></h4>

app/views/posts/_post.html.erb
<div class="post">
	<%= render :partial => 'posts/header', :as => :post, :object => post %>
	<%= simple_format(raw(auto_link(post.body))) %>
		
	<%= render :partial => 'book' unless @items.empty? %>
	
	<h4>Comments:</h4>
	<div id="comments">		
		<% unless @comments.empty? %>			
			<%= render :partial => 'comments/comment', :as => :comment, :collection => @comments  %>
		<% else %>
			<h4 id="no_comments">There are no user comments yet.</h4><br/>
		<% end %>	
	</div>

<% if user_signed_in? %>
	<div class="comment_form">
		<%= render :partial => 'comments/form', :locals => {:post => post} %>
	</div>		
<% else %>
  <%= link_to 'Sign in to comment', new_user_session_path %>
<% end %>

</div>

app/views/posts/_post_brief.html.erb
<div class="post">
	<%= render :partial => 'posts/header', :as => :post, :object => post %>
	<p><%= strip_tags(truncate(post.body, :length => 500, :separator => ' ', :omission => ' ...')) %></p>
	<p class="center"><%= link_to 'Read more >>', post %></p>
	<hr/>
</div>

app/views/posts/edit.html.erb
<% @page_title = 'Edit Post' %>
<h1>Edit Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %>

app/views/posts/index.html.erb
<%= will_paginate @posts %>

<% if admin? %>
	<%= link_to 'New Post', new_post_path %>
<% end %>

<% if @category %>
	<h2>Posts for <%= @category %></h2>
<% end %>

<%= render :partial => "posts/post_brief", :as => :post, :collection => @posts %>

app/views/posts/new.html.erb
<% @page_title = 'New Post' %>
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<% @page_title = @post.title %>

<% if admin? %>
	<%= link_to 'Edit Post', edit_post_path(@post) %>
<% end %>
<%= render @post %>